WebPracticeApp/Models/DefaultClass.cs
namespace WebPracticeApp.Models
{
  public class DefaultClass
  {

    public int Id { get; set; }
    public string MainText { get; set; }
    public string SecondaryText { get; set; }

    public DefaultClass()
    {

    }
  }
}

WebPracticeApp/Models/ErrorViewModel.cs
namespace WebPracticeApp.Models
{
  public class ErrorViewModel
  {
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
  }
}

WebPracticeApp/Controllers/DefaultClassesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebPracticeApp.Data;
using WebPracticeApp.Models;

namespace WebPracticeApp.Controllers
{
    public class DefaultClassesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DefaultClassesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: DefaultClasses
        public async Task<IActionResult> Index()
        {
            return View(await _context.DefaultClass.ToListAsync());
        }
        // GET: DefaultClasses/ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }
        // PoST: DefaultClasses/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(String SearchPhrase)
        {
            return View("Index", await _context.DefaultClass.Where( j => j.MainText.Contains(SearchPhrase)).ToListAsync());
    }
        
        // GET: DefaultClasses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var defaultClass = await _context.DefaultClass
                .FirstOrDefaultAsync(m => m.Id == id);
            if (defaultClass == null)
            {
                return NotFound();
            }

            return View(defaultClass);
        }

        [Microsoft.AspNetCore.Authorization.Authorize]
        // GET: DefaultClasses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DefaultClasses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Microsoft.AspNetCore.Authorization.Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MainText,SecondaryText")] DefaultClass defaultClass)
        {
            if (ModelState.IsValid)
            {
                _context.Add(defaultClass);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(defaultClass);
        }

        // GET: DefaultClasses/Edit/5
        [Microsoft.AspNetCore.Authorization.Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var defaultClass = await _context.DefaultClass.FindAsync(id);
            if (defaultClass == null)
            {
                return NotFound();
            }
            return View(defaultClass);
        }

        // POST: DefaultClasses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Microsoft.AspNetCore.Authorization.Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MainText,SecondaryText")] DefaultClass defaultClass)
        {
            if (id != defaultClass.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(defaultClass);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DefaultClassExists(defaultClass.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(defaultClass);
        }

        // GET: DefaultClasses/Delete/5
        [Microsoft.AspNetCore.Authorization.Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var defaultClass = await _context.DefaultClass
                .FirstOrDefaultAsync(m => m.Id == id);
            if (defaultClass == null)
            {
                return NotFound();
            }

            return View(defaultClass);
        }

        // POST: DefaultClasses/Delete/5
        [HttpPost, ActionName("Delete")]
        [Microsoft.AspNetCore.Authorization.Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var defaultClass = await _context.DefaultClass.FindAsync(id);
            _context.DefaultClass.Remove(defaultClass);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DefaultClassExists(int id)
        {
            return _context.DefaultClass.Any(e => e.Id == id);
        }
    }
}

WebPracticeApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebPracticeApp.Models;

namespace WebPracticeApp.Controllers
{
  public class HomeController : Controller
  {
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
      _logger = logger;
    }

    public IActionResult Index()
    {
      return View();
    }

    public IActionResult Privacy()
    {
      return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
      return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
  }
}

WebPracticeApp/Views/DefaultClasses/Create.cshtml
@model WebPracticeApp.Models.DefaultClass

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>DefaultClass</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MainText" class="control-label"></label>
                <input asp-for="MainText" class="form-control" />
                <span asp-validation-for="MainText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondaryText" class="control-label"></label>
                <input asp-for="SecondaryText" class="form-control" />
                <span asp-validation-for="SecondaryText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebPracticeApp/Views/DefaultClasses/Delete.cshtml
@model WebPracticeApp.Models.DefaultClass

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DefaultClass</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MainText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MainText)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondaryText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondaryText)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebPracticeApp/Views/DefaultClasses/Details.cshtml
@model WebPracticeApp.Models.DefaultClass

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>DefaultClass</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MainText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MainText)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondaryText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondaryText)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebPracticeApp/Views/DefaultClasses/Edit.cshtml
@model WebPracticeApp.Models.DefaultClass

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>DefaultClass</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="MainText" class="control-label"></label>
                <input asp-for="MainText" class="form-control" />
                <span asp-validation-for="MainText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondaryText" class="control-label"></label>
                <input asp-for="SecondaryText" class="form-control" />
                <span asp-validation-for="SecondaryText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebPracticeApp/Views/DefaultClasses/Index.cshtml
@model IEnumerable<WebPracticeApp.Models.DefaultClass>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MainText)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MainText)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

WebPracticeApp/Views/DefaultClasses/ShowSearchForm.cshtml
<h4>Search for text/entery</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">
            <div class="form-group">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebPracticeApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Vadym's Web App</h1>
    <p>Let's see how this works!<br />Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebPracticeApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebPracticeApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebPracticeApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebPracticeApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DefaultClasses" asp-action="Index">Main Juicer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DefaultClasses" asp-action="ShowSearchForm">Search</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebPracticeApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>